# Global Prochlorococcus Gene Prevalence Estimates

The purpose of this notebook is to generate a global estimate of the prevalence of every
known gene family in the Prochlorococcus pangenome.

In [1]:
from pathlib import Path

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from gene_prevalence import BernoulliPrevalenceModel

# instatiate random number generator with fixed seed for reproducibility
rng = np.random.default_rng(seed=9481)

# significance level for confidence intervals
ci_alpha = 0.05

In [2]:
# set aesthetic parameters

line_color = '#0F0A0A'    # dark

neutral_color = '#E0E0E0'

# thursday
accent_colors = ['#9B5DE5', '#FFAC69', '#00C9AE', '#FD3F92', '#0F0A0A', 
                 '#959AB1', '#FFDB66', '#63B9FF','#FFB1CA', '#4F1DD7']

style = {'axes.edgecolor': line_color,
         'axes.labelcolor': line_color,
         'text.color': line_color,
         'xtick.color': line_color,
         'ytick.color': line_color,
         'font.family': 'Helvetica',
         'font.Helvetica': ['Helvetica']}

palette = sns.color_palette(accent_colors)

sns.set_context('talk', rc={'lines.linewidth': 2})
sns.set_palette(palette)
sns.set_style('ticks', style)

plt.rcParams['legend.frameon'] = False
plt.rcParams['axes.spines.left'] = True
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.bottom'] = True
plt.rcParams['axes.facecolor'] = 'none'
plt.rcParams['figure.facecolor'] = 'none'
plt.rcParams['patch.linewidth'] = 0
plt.rcParams['patch.edgecolor'] = 'none'
plt.rcParams['savefig.dpi'] = 300

In [47]:
# import data

# directory paths
project_root = Path.cwd().resolve().parent
data_dir = project_root / "data" / "inputs"

# pro cell counts global climatology
pro_cell_counts_df = pd.read_csv(data_dir / "PRO_annual_climatological_mean.csv").rename(
    columns={"Latitude'": 'lat', "Longitude'": 'lon'}
)

# pro relative abundances by biome and clade
pro_rel_abund_df = pd.read_csv(data_dir / "Pro_Ecotype_Recipe_Rel_Abundance.csv")
pro_rel_abund_df['biome'] = pro_rel_abund_df['bin'].str.split('_').str[0]
pro_rel_abund_df['depth_bin'] = pro_rel_abund_df['bin'].str.split('_').str[1].map(
    {'upper50m': '0-50m', '50to100m': '50-100m', '100to200m': '100-200m'})

# lonhurst provinces shapefile
longhurst = gpd.read_file(data_dir / "longhurst_v4_2010/Longhurst_world_v4_2010.shp").to_crs("EPSG:4326")

longhurst

,ProvCode,ProvDescr,geometry
0,BPLR,Polar - Boreal Polar Province (POLR),"MULTIPOLYGON (((-161.18426 63.5, -161.5 63.5, ..."
1,ARCT,Polar - Atlantic Arctic Province,"MULTIPOLYGON (((-21.51305 64.64409, -21.55945 ..."
2,SARC,Polar - Atlantic Subarctic Province,"MULTIPOLYGON (((11.26472 63.96082, 11.09548 63..."
3,NADR,Westerlies - N. Atlantic Drift Province (WWDR),"POLYGON ((-11.5 57.5, -11.5 56.5, -11.5 55.5, ..."
4,GFST,Westerlies - Gulf Stream Province,"POLYGON ((-43.5 43.5, -43.5 42.5, -43.5 41.5, ..."
5,NASW,Westerlies - N. Atlantic Subtropical Gyral Pro...,"POLYGON ((-39.5 25.5, -40.5 25.5, -41.5 25.5, ..."
6,NATR,Trades - N. Atlantic Tropical Gyral Province (...,"MULTIPOLYGON (((-72.34673 18.53597, -72.36877 ..."
7,WTRA,Trades - Western Tropical Atlantic Province,"POLYGON ((-19.5 -6.5, -20.5 -6.5, -21.5 -6.5, ..."
8,ETRA,Trades - Eastern Tropical Atlantic Province,"POLYGON ((9.5 -12.5, 8.5 -12.5, 7.5 -12.5, 6.5..."
9,SATL,Trades - South Atlantic Gyral Province (SATG),"POLYGON ((-19.5 -6.5, -18.5 -6.5, -17.5 -6.5, ..."
10,NECS,Coastal - NE Atlantic Shelves Province,"POLYGON ((10.97944 54.38056, 10.99458 54.37749..."
11,CNRY,Coastal - Canary Coastal Province (EACB),"MULTIPOLYGON (((-16.33947 11.5, -16.38454 11.5..."
12,GUIN,Coastal - Guinea Current Coastal Province,"MULTIPOLYGON (((-15.42389 11.67611, -15.42931 ..."
13,GUIA,Coastal - Guianas Coastal Province,"MULTIPOLYGON (((-35.5 -3.5, -35.5 -4.5, -34.5 ..."
14,NWCS,Coastal - NW Atlantic Shelves Province,"MULTIPOLYGON (((-82.46584 27.73291, -82.5 27.6..."
15,MEDI,"Westerlies - Mediterranean Sea, Black Sea Prov...","MULTIPOLYGON (((34.98966 29.5, 34.91623 29.5, ..."
16,CARB,Trades - Caribbean Province,"POLYGON ((-82.5 27.95346, -82.5 27.6951, -82.5..."
17,NASE,Westerlies - N. Atlantic Subtropical Gyral Pro...,"POLYGON ((-19.5 25.5, -20.5 25.5, -21.5 25.5, ..."
18,BRAZ,Coastal - Brazil Current Coastal Province,"POLYGON ((-33.5 -10.5, -33.5 -11.5, -33.5 -12...."
19,FKLD,Coastal - SW Atlantic Shelves Province,"MULTIPOLYGON (((-68.9932 -54.43104, -68.99487 ..."
20,BENG,Coastal - Benguela Current Coastal Province,"POLYGON ((11.71697 -17.5, 11.71639 -17.53917, ..."
21,MONS,Trades - Indian Monsoon Gyres Province,"MULTIPOLYGON (((80.61033 9.44472, 80.56945 9.4..."
22,ISSG,Trades - Indian S. Subtropical Gyre Province,"POLYGON ((117.5 -16.5, 117.5 -17.5, 117.5 -18...."
23,EAFR,Coastal - E. Africa Coastal Province,"POLYGON ((48.50315 -13.5, 48.50388 -13.51555, ..."
24,REDS,"Coastal - Red Sea, Persian Gulf Province","MULTIPOLYGON (((34.57215 28.0959, 34.62478 28...."
25,ARAB,Coastal - NW Arabian Upwelling Province,"MULTIPOLYGON (((39.5 -7.5, 39.28814 -7.5, 39.2..."
26,INDE,Coastal - E. India Coastal Province,"POLYGON ((97.93498 14.5, 97.5 14.5, 96.5 14.5,..."
27,INDW,Coastal - W. India Coastal Province,"MULTIPOLYGON (((80.5 9.5, 80.5 9.47885, 80.493..."
28,AUSW,Coastal - Australia-Indonesia Coastal Province,"MULTIPOLYGON (((125.66081 -14.61166, 125.64224..."
29,BERS,Polar - N. Pacific Epicontinental Province,"MULTIPOLYGON (((126.68849 37.83391, 126.68054 ..."
30,PSAE,Westerlies - Pacific Subarctic Gyres Province ...,"POLYGON ((-134.5 50.5, -134.5 49.5, -134.5 48...."
31,PSAW,Westerlies - Pacific Subarctic Gyres Province ...,"MULTIPOLYGON (((148.54026 45.44777, 148.46051 ..."
32,KURO,Westerlies - Kuroshio Current Province,"MULTIPOLYGON (((124.74987 10.5, 124.5 10.5, 12..."
33,NPPF,Westerlies - N. Pacific Polar Front Province,"MULTIPOLYGON (((156.5 34.5, 155.5 34.5, 155.5 ..."
34,NPSW,Westerlies - N. Pacific Subtropical Gyre Provi...,"MULTIPOLYGON (((-175.5 28.5, -175.5 27.5, -175..."
35,TASM,Westerlies - Tasman Sea Province,"MULTIPOLYGON (((174.5 -35.89155, 174.5 -35.994..."
36,SPSG,Westerlies - S. Pacific Subtropical Gyre Province,"MULTIPOLYGON (((174.79553 -37.02306, 174.88748..."
37,NPTG,Trades - N. Pacific Tropical Gyre Province,"POLYGON ((-114.5 16.5, -114.5 15.5, -114.5 14...."
38,PNEC,Trades - N. Pacific Equatorial Countercurrent ...,"POLYGON ((-82.5 0.5, -83.5 0.5, -84.5 0.5, -85..."
39,PEQD,Trades - Pacific Equatorial Divergence Province,"POLYGON ((-86.5 0.5, -86.5 -0.5, -86.5 -1.5, -..."
40,WARM,Trades - W. Pacific Warm Pool Province,"MULTIPOLYGON (((-175.5 1.5, -175.5 0.5, -175.5..."
41,ARCH,Trades - Archipelagic Deep Basins Province,"MULTIPOLYGON (((128.69141 -3.50004, 128.67804 ..."
42,ALSK,Coastal - Alaska Downwelling Coastal Province,"MULTIPOLYGON (((-127.5 50.5868, -127.5 50.5627..."
43,CCAL,Coastal - California Upwelling Coastal Province,"MULTIPOLYGON (((-110.5 24.5, -110.5 24.22013, ..."
44,CAMR,Coastal - Central American Coastal Province,"MULTIPOLYGON (((-80.44239 -0.5, -80.5 -0.5, -8..."
45,CHIL,Coastal - Chile-Peru Current Coastal Province,"POLYGON ((-80.5 -0.37114, -80.50118 -0.37257, ..."
46,CHIN,Coastal - China Sea Coastal Province,"MULTIPOLYGON (((128.5 35.12007, 128.5 35.01085..."
47,SUND,Coastal - Sunda-Arafura Shelves Province,"MULTIPOLYGON (((113.67269 -8.5, 113.5 -8.5, 11..."
48,AUSE,Coastal - East Australian Coastal Province,"POLYGON ((154.5 -33.5, 154.5 -34.5, 154.5 -35...."
49,NEWZ,Coastal - New Zealand Coastal Province,"MULTIPOLYGON (((168.56387 -46.58466, 168.55164..."
50,SSTC,Westerlies - S. Subtropical Convergence Province,"MULTIPOLYGON (((180 -41.5, 179.5 -41.5, 179.5 ..."
51,SANT,Westerlies - Subantarctic Province,"MULTIPOLYGON (((-69.16417 -54.51973, -69.14903..."
52,ANTA,Polar - Antarctic Province,"POLYGON ((180 -57.5, 180 -67.5, 179.5 -67.5, 1..."
53,APLR,Polar - Austral Polar Province,"MULTIPOLYGON (((-83.5 -78.5, -83.71472 -78.5, ..."

In [40]:
# calculate multiplication factors for each depth range

# aggregate cell counts into three depth ranges: 0-50m, 50-100m, and 100-200m
pro_cell_counts_df['0-50m'] = pro_cell_counts_df.loc[:, "0m'":"50m'"].mean(axis=1)
pro_cell_counts_df['50-100m'] = pro_cell_counts_df.loc[:, "50m'":"100m'"].mean(axis=1)
# multiply by two to account for twice the volume in this depth range
pro_cell_counts_df['100-200m'] = pro_cell_counts_df.loc[:, "100m'":"200m'"].mean(axis=1) * 2

# downsample to only include rows with non-null values in at least one of the depth ranges
pro_agg_df = pro_cell_counts_df[pro_cell_counts_df[['0-50m', '50-100m', '100-200m']].notnull().any(
    axis=1)][['lat', 'lon', '0-50m', '50-100m', '100-200m']].reset_index(drop=True)

# join longhurst provinces with pro cell counts
gridded_pro_df = gpd.GeoDataFrame(
    pro_agg_df,
    geometry=gpd.points_from_xy(pro_agg_df['lon'], pro_agg_df['lat']),
    crs="EPSG:4326"
)

# attach province information to each point
# NOTE: within or intersects?
gridded_pro_df = gpd.sjoin(
    gridded_pro_df, longhurst, how='left', predicate='intersects')

# identify biome for each point based on province information
gridded_pro_df['biome'] = gridded_pro_df['ProvDescr'].str.split(' - ').str[0]

# aggregate by biome to get multiplication factor for each biome
pro_factors_df = gridded_pro_df.groupby('biome')[['0-50m', '50-100m', '100-200m']].sum()

# drop polar biome
pro_factors_df = pro_factors_df.loc[pro_factors_df.index != 'Polar']

# normalize by the minimum value across all biomes and depth ranges to get multiplication factors
pro_factors_df = pro_factors_df / pro_factors_df.min().min()

pro_factors_df

                0-50m    50-100m  100-200m
biome
Coastal      2.352964   1.647873  1.000000
Trades      14.093870  12.402838  9.713393
Westerlies   6.094294   5.724519  6.418759

In [61]:
# calculate global relative abundances

# add on multiplication factors to pro relative abundances dataframe
global_rel_abund_df = pro_rel_abund_df.merge(
    pro_factors_df.reset_index().melt(var_name='depth_bin', id_vars='biome', value_name='factor'), 
    on=['biome', 'depth_bin'], 
    how='left'
)

# multiply relative abundances by multiplication factors to get global relative abundances
global_rel_abund_df['multiplied_rel_abundance'] = global_rel_abund_df['rel_abundance'] * global_rel_abund_df['factor']

# aggregate by clade to get global relative abundance for each clade
pro_global_rel_abund_df = global_rel_abund_df.groupby('clade')['multiplied_rel_abundance'].sum()
pro_global_rel_abund_df = pro_global_rel_abund_df / pro_global_rel_abund_df.sum()
pro_global_rel_abund_df = pro_global_rel_abund_df.reset_index().rename(
    columns={'multiplied_rel_abundance': 'global_rel_abundance'})

pro_global_rel_abund_df

              clade  global_rel_abundance
0           HL-I/VI              0.042424
1   HL-unclassified              0.021326
2             HL/LL              0.032114
3               HLI              0.175874
4              HLII              0.437426
5              HLVI              0.002432
6   LL-unclassified              0.040201
7               LLI              0.140869
8          LLII-III              0.009637
9              LLIV              0.008812
10               PR              0.088884